name: Cypress API Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'cypress/e2e/api/**'
      - 'cypress/fixtures/**'
      - 'cypress/support/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'cypress/e2e/api/**'
      - 'cypress/fixtures/**'
      - 'cypress/support/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-api:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Correr tests API
        run: npm run cy:api
        env:
          CYPRESS_API_URL:      ${{ secrets.API_URL }}
            
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: cypress/reports/

  deploy:
    name: Publicar Reporte API
    needs: cypress-api
    runs-on: ubuntu-latest
    if: always()

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5